config/routes.rb
Rails.application.routes.draw do
  get 'homes/home'
  get 'rooms/index'
  get 'rooms/new'
  get 'rooms/create'
  get 'reservations/index'
  
  get '/account',to:'users#account'
  get '/profile',to:'users#profile'
  devise_for :users,controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root to: "homes#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/',to:'homes#home'
  
  resources :users
  get 'rooms/search',to:'rooms#search'
  get 'rooms/posts',to:'rooms#posts'
  resources :rooms
  resources :reservations
   
 

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reser.rb
class Reser < ApplicationRecord
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :user
    belongs_to :room

  validates :person, presence:true
  validate :start_date_check
  validate :start_end_check
  
  def start_date_check 
    errors.add(:start_date,"に過去の日付は指定できません") if start_date.nil? || start_date < Date.today
  end
  def start_end_check
    errors.add(:end_date,"は開始日より後の日付を指定してください") if end_date.nil? || start_date > end_date
  end  
  
end

app/models/ro_reg.rb
class RoReg < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_one_attached :picture
  has_many :reservations
    
   
  validates :name,presence:true
  validates :information,presence:true
  validates :price,presence:true,numericality:true
  validates :address,presence:true
  validates :picture,presence:true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
  validates :name, presence: true
  validates :introduction, length: { maximum: 200 } 

  has_one_attached :image
  has_many :rooms
  has_many :reservations
   
  validates :introduction,presence: true, on: :update
  validates :image,presence: true, on: :update

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
   
   before_action:configure_permitted_parameters,if: :devise_controller?
  
   private
    
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys: [:name]) 
      
      devise_parameter_sanitizer.permit(:edit,keys: [:name,:introduction,:image])
  
    end
    
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def home
        
    end
    
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def home
  end
end

app/controllers/resers_controller.rb
class ResersController < ApplicationController
  def index
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @user = current_user
    @reservation = Reservation.where(user_id: @user.id)
  end

  def new 
    @reservation = Reservation.new(params_reservation)
    if @reservation.valid?
      @room = Room.find(@reservation.room_id)
      @days = (@reservation.end_date - @reservation.start_date).to_i
      @price = @room.price*@days*@reservation.person
    else
      @room = Room.find(@reservation.room_id)
      @user = User.find(@room.user_id)
      @reserv = current_user
      if user_signed_in?
        @user_check = User.exists?(id: @reserv.id,introduction: nil)
      end      
      render template:"rooms/show"
    end
  end

  def create
    @reservation = Reservation.new(params_reservation)
    if @reservation.save
      flash[:notice]="ルームの予約が完了しました"
      redirect_to reservation_path(@reservation.id)
    else 
      flash[:notice]="ルームの予約に失敗しました"
      render "new"
    end
    
  end

  def show
    @reservation = Reservation.find(params[:id])
    @room = Room.find(@reservation.room_id)
  end
  
  def edit
  end

  def update
  end

  def destroy
  end
  
  private
  def params_reservation
    params.require(:reservation).permit(:user_id,:room_id,:start_date,:end_date,:person,:total_price)
  end
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  end

  def new
    @user =current_user
    @user_check = User.exists?(id: @user.id,introduction: nil)
    @room = Room.new
  end

  def create
    @room = Room.new(rooms_params)
    @room.user_id = current_user.id
    if @room.save
      flash[:notice] = "ルームの新規登録が完了しました"
      redirect_to room_path(@room.id)
    else
      @user =current_user
      @user_check = User.exists?(id: @user.id,introduction: "")
      render "new"
    end
  end

 
  def posts
    @user = current_user
    @room = Room.where(user_id:@user.id) 
  end
  
  def show
    @room = Room.find(params[:id])
    @user = User.find(@room.user_id)
    @reserv = current_user
    @reservation =Reservation.new
    if user_signed_in?
      @user_check = User.exists?(id: @reserv.id,introduction: nil)
    end
  end

  def search
    if params[:area] == nil && params[:keyword] == nil
      @room = Room.all
      @cnt = Room.all.count
    elsif params[:area] == "" && params[:keyword] == ""
      @room = Room.all
      @cnt = Room.all.count
    elsif params[:area] 
      @room = Room.where("address LIKE?",'%'+params[:area]+'%')
      @cnt = Room.where("address LIKE?",'%'+params[:area]+'%').count
    elsif  params[:keyword] 
      @room = Room.where("name LIKE?",'%'+params[:keyword]+'%').or(Room.where("address LIKE?",'%'+params[:keyword]+'%')).or(Room.where("information LIKE?",'%'+params[:keyword]+'%')) .or(Room.where("price LIKE?",'%'+params[:keyword]+'%')) 
      @cnt = Room.where("name LIKE?",'%'+params[:keyword]+'%').or(Room.where("address LIKE?",'%'+params[:keyword]+'%')).or(Room.where("information LIKE?",'%'+params[:keyword]+'%')) .or(Room.where("price LIKE?",'%'+params[:keyword]+'%')) .count
    else
    end
  end

  def edit
  end

  def update
  end


  def rooms_params
    params.require(:room).permit(:user_id,:name,:information,:price,:address,:picture)
  end
end 

app/controllers/roregs_controller.rb
class RoregsController < ApplicationController
  def index
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user!
 
 
 def account
   @user= current_user
 end

 def profile
   @user= current_user
 end

 def update
   @user = current_user
   if @user.update(params.require(:user).permit(:name,:introduction,:image))
     flash[:notice] = "ユーザープロフィールの情報を更新しました"
     redirect_to profile_path
   else
     render "profile"
   end  
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/resers_helper.rb
module ResersHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/roregs_helper.rb
module RoregsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/home.html.erb
<div class="top-main">
  <div class="container h-100">
    <div class="row h-100">
      <div class="col-6 form-frame">
        <div class="form-area">
          <p class="form-area-title">poteshareで</br>まだ体験したことのない旅をしよう</p>
          <div class="form-area-search">
            <%= form_with url: rooms_search_path,method: :get,local: true do |f| %>
              <div class="text-left">エリア</div>  
              <%= f.text_field :area ,placeholder:"東京", class:"w-100 form-controll" %>
              <%= submit_tag "探す", class:"w-100 form-controll btn btn-primary form-controll-submit"%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="panel-area m-5">
    <h1 class="panel-title">おすすめのエリア</h1>
    <div class="row">
      <div class="panel-item col-3">
        <%= link_to '/rooms/search?utf8=%E2%9C%93&area=%E6%9D%B1%E4%BA%AC',class:"room-link" do %>
          <span>東京</span>
          <%=image_tag "img_tokyo.jpeg",class:"panel-image" %>
        <% end %>  
      </div>
      <div class="panel-item col-3">
        <%= link_to '/rooms/search?utf8=%E2%9C%93&area=%E5%A4%A7%E9%98%AA',class:"room-link" do %>
          <span>大阪</span>
          <%=image_tag "img_osaka.jpeg",class:"panel-image" %>
        <% end %>  
      </div>
      <div class="panel-item col-3">
        <%= link_to '/rooms/search?utf8=%E2%9C%93&area=%E4%BA%AC%E9%83%BD',class:"room-link" do %>
          <span>京都</span>
          <%=image_tag "img_kyoto.jpeg",class:"panel-image" %>
        <% end %>  
      </div>
      <div class="panel-item col-3">
        <%= link_to '/rooms/search?utf8=%E2%9C%93&area=%E5%8C%97%E6%B5%B7%E9%81%93',class:"room-link" do %>
          <span>北海道</span>
          <%=image_tag "img_sapporo.jpeg",class:"panel-image" %>
        <% end %>  
      </div>
    </div>
  </div>
</div>

app/views/resers/index.html.erb
<h1>Resers#index</h1>
<p>Find me in app/views/resers/index.html.erb</p>

app/views/reservations/index.html.erb
<div class="container-fiuld reservations">
  <h4 class="pb-4">予約済みルーム一覧</h4>
  <table>
    <thead>
      <tr class="text-center">
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>合計料金</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>予約確定日時</th>
      </tr>
    </thead>
    <tbody>
      <% @reservation.each do |r| %>
        <tr>
          <td>
          <%= link_to room_path(r.room.id) do %>
            <%= image_tag r.room.picture,size:"240x140" %>
          <% end %>  
          </td>
          <td>
          <%= link_to r.room.name, room_path(r.room.id) ,class:"reservation-room-name" %>
          </td>

          <td>
            <%= r.room.information %>
          </td>
         
          <td>
            <%= r.start_date %>
          </td>
          <td>
            <%= r.end_date %>
          </td>
          <td>
            <%= r.total_price %>
          </td>
          <td>
            <%= r.updated_at%>
          </td>

      
      
        </tr>
      <% end %>  
    </tbody>
  </table>
</div>  

app/views/reservations/new.html.erb
<div class="container reservation-new">
  <div class="row">
    <div class="col-6 offset-3">
      <div class="reservation-new-nav">
        <h4 class="reservation-new-title">予約確認画面</h4>
        <h5 class="price-icon"><%= @room.price %> /円</h5>
        <div class="reservations-new-date-select">

          <%=form_with model:@reservation do |r| %>
            <div>開始日</div>
            <%= r.date_field :start_date ,:value =>@reservation.start_date,class:"form-control mb-4 w-100" %>
            <div>終了日</div>
            <%= r.date_field :end_date ,:value =>@reservation.end_date,class:"form-control mb-4 w-100" %>
            <div>使用日数：<%= @days %>日　</div>
            <div>人数</div>
            <%= r.text_field :person ,:value =>@reservation.person,class:"form-control mb-4 w-100" %>
            <div>合計金額</div>
            <%= r.text_field :total_price ,:value =>@price,class:"form-control mb-4 w-100" %>
            <%= r.hidden_field :room_id, :value =>@reservation.room_id %>
            <%= r.hidden_field :user_id, :value =>@reservation.user_id %>
            <%= r.submit "予約を確定する",class:"btn btn-primary w-100 mb-2" %>
            <%= link_to "ルーム詳細に戻る",room_path(@room.id) ,class:"btn btn-secondary w-100"%>
          <% end %>  
        </div>
      </div>
    </div>  
  </div>
</div>

app/views/reservations/show.html.erb
<div class="container-fiuld user">
  <div class="row">
    <div class="col-12 reservation-view">
      <div class="reservation-view-box">
        <div class="reservation-box">
          <div class="row reservation-content"> 
            <label class="col-3">予約した部屋</label>
            <div class="col-9">
              <%=link_to @room.name,room_path(@room.id),class:"room-link" %>
            </div>  
          </div>
          <div class="row reservation-content"> 
            <label class="col-3">開始日</label>
            <div class="col-9">
              <%= @reservation.start_date %>
            </div>  
          </div>
          <div class="row reservation-content"> 
            <label class="col-3">終了日</label>
            <div class="col-9">
              <%= @reservation.end_date %>
            </div>  
          </div>
          <div class="row reservation-content"> 
            <label class="col-3">価格</label>
            <div class="col-9">
              <%= @reservation.total_price %>円
            </div>  
          </div>
        </div>  
      </div>
    </div>  
  </div> 

app/views/rooms/new.html.erb
<%if @user_check == false %>
  <div class="container room-show-container"> 
    <div class="row">
      <div class="col-2">
        <%=render "shared/roombar" %>
      </div>
      <div class="col-10 room-view">
        <div class="room-new-box">
          <%= form_with model:@room ,url:rooms_path,local:true,method: :post do |r| %>
            <div class="room-new-field mb-3 ">
              <h3>ルーム情報登録</h3>
            </div>
            <div class="room-new-field mb-5 ">
              <%=render "shared/error",obj:@room %>
            </div>
            <div class="room-new-field mb-3 ">
              <div class="row">
                <div class="col-3">
                  <label>ルーム名</label>
                  <span class="badge badge-danger">必須</span>
                </div>
                <div class="col-9">
                  <%= r.text_field :name,class:"w-100" %>
                </div>
              </div>
            </div>

            <div class="room-new-field mb-3 ">
              <div class="row">
                <div class="col-3">
                <label>ルーム紹介</label>
                  <span class="badge badge-danger">必須</span> 
                </div>
                <div class="col-9">
                  <%= r.text_area :information,class:"w-100" %>
                </div>
              </div>
            </div>

            <div class="room-new-field mb-3 ">
              <div class="row">
                <div class="col-3">
                <label>料金</label>
                  <span class="badge badge-danger">必須</span>
                </div>
                <div class="col-9">
                  <%= r.text_field :price,type:"number",class:"w-100" %>
                </div>
              </div>
            </div>

            <div class="room-new-field mb-3 ">
              <div class="row">
                <div class="col-3">
                <label>住所</label>
                  <span class="badge badge-danger">必須</span>
                </div>
                <div class="col-9">
                  <%= r.text_field :address,class:"w-100" %>
                </div>
              </div>
            </div>

            <div class="room-new-field mb-3 ">
              <div class="row">
                <div class="col-3">
                <label>ルーム画像</label> 
                  <span class="badge badge-danger">必須</span>
                </div>
                <div class="col-9">
                  <%= r.file_field :picture %>
                </div>
              </div>
            </div>

            <div class="col-3 p-0">
              <%= r.submit "登録", class:"p-2 m-1 btn-outline-primary text-white bg-primary col-12 rounded" %>
            </div> 
        <% end %>  
      </div>
    </div>
  </div>  

<%else%>
  <div class="container room-show-container room-profile-access"> 
    <h3>ルーム登録を行うには、プロフィールの編集を行ってください</h3>
    <%= link_to "プロフィール編集画面へ",profile_path ,class:"btn btn-primary"%>
  </div>  

<%end%>

app/views/rooms/post.html.erb
<div class="room-posts">
  <h4 class="pd-4">登録済みルーム一覧</h4>
  <table class="posts-table">
  <thead>
    <tr>
      <th>ルーム画像</th>
      <th>ルーム名</th>
      <th>ルーム紹介</th>
      <th>料金</th>
      <th>作成日</th>
    </tr>
  </thead>
  <tbody>
    <% @room.each do |room| %>
      <tr>
        <td>
          <%= image_tag room.picture,:size => "200x200"%>
        </td>
        <td class="posts-name"><%=link_to room.name,room_path(room.id) %></td>
        <td><%= room.information %></td>
        <td>¥<%= room.price %></td>
        <td><%= room.created_at %></td>
      </tr> 
    <% end %>
  </tbody>
  </table>
</div>

app/views/rooms/search.html.erb
<div class="room">
  <div class="row">
    <% if @room.present? %>
      <h3 class="col-12 search-number">検索結果 <%= @cnt %>件です</h3> 
      <% @room.each do |room| %>
        <div class="col-3">
          <div class="room-search-frame">
            <%= link_to room_path(room.id),class:"room-link" do %>
              <div class="search-profile-image">
                <%= image_tag room.picture ,width:"100%",height:"100%",class:"pt-3" %>
              </div>
              <div class="room-search-profile">
                <div class="search-profile-name"><%= room.name %></div>
                <div class="search-profile-address"><%= room.address %></div>
                <div class="search-profile-price">¥<%= room.price %></div>
              </div>
            <% end %>
          </div>
        </div> 
      <% end %>  
    <% else %>
      <h3>検索結果はありませんでした</h3>  
    <% end %> 
  </div>
</div>

app/views/rooms/show.html.erb
<div class="clearfix">
  <%= render "shared/error_form",{ object:@reservation, url: new_reservation_path } %>
</div>
<div class="container room-show">
  <div class="row">
    <div class="col-8">
      <%= image_tag @room.picture ,class:"w-100 room-show-picture" %>
      <div class="room-show-detile  mt-5">
        <div class="room-show-detile-icon">
          <%= image_tag @user.image ,style: "border-radius: 50%",:size => "70x70" %>
        </div> 
        <div class="room-show-profile ml-4">
          <p class="room-show-profile-name"><%= @room.name %></p>
          <p class="room-show-profile-adress"><%= @room.address %></p>
        </div>  
      </div>    
      <p class="mt-3 room-show-profile-intro"><%= @room.information %></p>
      
    </div>
    <div class="col-4">
      <div class="room-show-nav">
        <h5 class="price-icon"><%= @room.price %> /円</h5>
        <div class="room-show-date-select">
          <%=form_with model:@reservation ,url: new_reservation_path,local:true,method: :get do |r| %>
            <label>開始日</label>
            <%= r.date_field :start_date ,class:"room-show-form mb-4 w-100" %>
            <label>終了日</label>
            <%= r.date_field :end_date ,class:"room-show-form mb-4 w-100" %>
            <label>人数</label>
            <%= r.text_field :person, type:"number" ,class:"room-show-form mb-4 w-100" %>
     
            <% if @user_check == true %>
              <%= link_to "プロフィールを編集する", profile_path,class:"btn btn-secondary w-100" %>
            <% elsif @user_check == false  %>
              <%= r.hidden_field :user_id ,:value =>@reserv.id ,class:"room-show-form mb-4" %>
              <%= r.hidden_field :room_id ,:value =>@room.id ,class:"room-show-form mb-4" %>
              <%= submit_tag "予約する" ,class:"btn btn-primary w-100" %>             
            <% else %>
              <%= link_to "ログインする", "/users/sign_in",class:"btn btn-secondary w-100" %>
            <% end %>
          <% end %>  
        </div>
        </div>
    </div>
  </div>
</div>

app/views/roregs/index.html.erb
<h1>Roregs#index</h1>
<p>Find me in app/views/roregs/index.html.erb</p>