config/routes.rb
Rails.application.routes.draw do
  get 'homes/home'
  get 'rooms/index'
  get 'rooms/new'
  get 'rooms/create'
  get 'reservations/index'
  
  get '/account',to:'users#account'
  get '/profile',to:'users#profile'
  devise_for :users,controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root to: "homes#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/',to:'homes#home'
  
  resources :users
  get 'rooms/search',to:'rooms#search'
  get 'rooms/posts',to:'rooms#posts'
  resources :rooms
  resources :reservations
   
 

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reser.rb
class Reser < ApplicationRecord
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :user
    belongs_to :room

  validates :person, presence:true
  validate :start_date_check
  validate :start_end_check
  
  def start_date_check 
    errors.add(:start_date,"に過去の日付は指定できません") if start_date.nil? || start_date < Date.today
  end
  def start_end_check
    errors.add(:end_date,"は開始日より後の日付を指定してください") if end_date.nil? || start_date > end_date
  end  
  
end

app/models/ro_reg.rb
class RoReg < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_one_attached :picture
  has_many :reservations
    
   
  validates :name,presence:true
  validates :information,presence:true
  validates :price,presence:true,numericality:true
  validates :address,presence:true
  validates :picture,presence:true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
  validates :name, presence: true
  validates :introduction, length: { maximum: 200 } 

  has_one_attached :image
  has_many :rooms
  has_many :reservations
   
  validates :introduction,presence: true, on: :update
  validates :image,presence: true, on: :update

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
   
   before_action:configure_permitted_parameters,if: :devise_controller?
  
   private
    
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys: [:name]) 
      
      devise_parameter_sanitizer.permit(:edit,keys: [:name,:introduction,:image])
  
    end
    
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def home
        
    end
    
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def home
  end
end

app/controllers/resers_controller.rb
class ResersController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  end

  def new
    @user =current_user
    @user_check = User.exists?(id: @user.id,introduction: nil)
    @room = Room.new
  end

  def create
    @room = Room.new(rooms_params)
    @room.user_id = current_user.id
    if @room.save
      flash[:notice] = "ルームの新規登録が完了しました"
      redirect_to room_path(@room.id)
    else
      @user =current_user
      @user_check = User.exists?(id: @user.id,introduction: "")
      render "new"
    end
  end

 
  def posts
    @user = current_user
    @room = Room.where(user_id:@user.id) 
  end
  
  def show
    @room = Room.find(params[:id])
    @user = User.find(@room.user_id)
    @reserv = current_user
    @reservation =Reservation.new
    if user_signed_in?
      @user_check = User.exists?(id: @reserv.id,introduction: nil)
    end
  end

  def search
    if params[:area] == nil && params[:keyword] == nil
      @room = Room.all
      @cnt = Room.all.count
    elsif params[:area] == "" && params[:keyword] == ""
      @room = Room.all
      @cnt = Room.all.count
    elsif params[:area] 
      @room = Room.where("address LIKE?",'%'+params[:area]+'%')
      @cnt = Room.where("address LIKE?",'%'+params[:area]+'%').count
    elsif  params[:keyword] 
      @room = Room.where("name LIKE?",'%'+params[:keyword]+'%').or(Room.where("address LIKE?",'%'+params[:keyword]+'%')).or(Room.where("information LIKE?",'%'+params[:keyword]+'%')) .or(Room.where("price LIKE?",'%'+params[:keyword]+'%')) 
      @cnt = Room.where("name LIKE?",'%'+params[:keyword]+'%').or(Room.where("address LIKE?",'%'+params[:keyword]+'%')).or(Room.where("information LIKE?",'%'+params[:keyword]+'%')) .or(Room.where("price LIKE?",'%'+params[:keyword]+'%')) .count
    else
    end
  end

  def edit
  end

  def update
  end


  def rooms_params
    params.require(:room).permit(:user_id,:name,:information,:price,:address,:picture)
  end
end 

app/controllers/roregs_controller.rb
class RoregsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user!
 
 
 def account
   @user= current_user
 end

 def profile
   @user= current_user
 end

 def update
   @user = current_user
   if @user.update(params.require(:user).permit(:name,:introduction,:image))
     flash[:notice] = "ユーザープロフィールの情報を更新しました"
     redirect_to profile_path
   else
     render "profile"
   end  
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/resers_helper.rb
module ResersHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/roregs_helper.rb
module RoregsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/profile.html.erb
<div class="row h-100">
  <div class="col-2 sidebar">
    <%= render "shared/sidebar" %>
  </div>

  <div class="col-10 user-account">
    <div class="user-account-box">
    
      <%=form_with model:@user do |f|%>
      
        <h4 class="mb-3 mr-5 ml-5 row">プロフィール</h4>
        <%= render "shared/error",obj:@user %>
        <div class="mr-10 ml-5 row ">
          <div class="col-10 mb-5 text-center ">
            <% if @user.image.attached? %>
              <%= image_tag @user.image ,style: "border-radius: 50%",:size => "100x100" %>
            <%else%>
              <%= image_tag "upper_body-2.png",style: "border-radius: 50%",:size => "100x100"%>  
            <% end %>
          </div>
        </div>  
        <div class="mb-5 mr-5 ml-5 row">
          <div class="col-3">
            <label for="exampleFormControlInput1" class="form-label">アイコン画像</label>
            <span class="badge badge-danger">必須</span>
          </div>
          <div class="col-8">
            <%= f.file_field :image,class:"col-12"%>
          </div> 
        </div>
        <div class="mb-5 mr-5 ml-5 row">
          <div class="col-3">
            <label for="exampleFormControlInput1" class="form-label ">名前</label>
            <span class="badge badge-danger">必須</span>
          </div>
          <div class="col-9">
            <%= f.text_field:name,class:"col-12 form-control"%>
          </div> 
        </div>
        <div class="mb-5 mr-5 ml-5 row">
          <div class="col-3">
            <label for="exampleFormControlTextarea1" class="form-label ">自己紹介</label>
            <span class="badge badge-danger">必須</span>
          </div> 
          <div class="col-9">  
            <%= f.text_area:introduction,class:"col-12 intoroduction-form" %>
          </div>  
        </div>
        <div class="ml-5 col-3">
         <%= f.submit "更新", class:" p-2 m-1 btn-outline-primary text-white bg-primary col-12 rounded" %>
        </div> 
      
      <% end %>
    </div>  
  </div>
</div>

					

app/views/accounts/user.html.erb
<div class="row">
  <div class="col-2 sidebar">
    <%= render "shared/sidebar" %>
  </div>
  <div class="col-10 user-account">
    <div class="user-account-box w-880">
  
      <h4 class="mb-3 mr-5 ml-5 row">アカウント</h4>
      <div class="mb-5 mr-5 ml-5 row">
        <label for="staticEmail" class="col-sm-3 col-form-label">メールアドレス</label>
        <div class="col-9">
          <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="email@example.com">
        </div>
      </div>
      <div class="mb-5 mr-5 ml-5 row">
        <label for="inputPassword" class="col-sm-3 col-form-label">パスワード</label>
        <div class="col-9">********</div>
      </div>
      <div class="mb-3 mr-10 ml-5 row">
        <%=link_to"編集","/users/edit",class:"btn btn-primary text-white p-2 m-1 btn-outline-primary text-white bg-primary rounded col-2"%>
      </div>
    </div>
  </div>
</div>

					

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PTPNRT2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "shared/header" %>
    </header>
    <main>
      <div class="clearfix">
        <%= notice %>
        <%= alert %>
      </div>
      <%= yield %>
    </main>
    <footer>
      <%= render "shared/footer" %>
    </footer>
  </body>
</html>



<!--<!DOCTYPE html>
<html>
  <head>
    <title>PTPNRT2</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>      
          <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 header-container shadow-sm">
              <div class="header-left-container">
                <%= link_to root_path do %>
                <img class="my-0 mr-md-auto font-weight-normal" id="home-logo" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png">
                <% end %>

                <div class="header-search-container mt-3">
                  <div class="header-search-box">
                    <%= form_with url: rooms_search_path,method: :get,local: true do |f| %>
                      <%= f.text_field :area ,placeholder:"エリア検索",class:"header-search-input"%>
                      <% submit_tag %>
                    <% end %>
                    <i class="fas fa-map-marker-alt"></i>
                  </div>
                  
                  <div class="header-search-box">
                    <%= form_with url: rooms_search_path,method: :get,local: true do |f| %>
                      <%= f.text_field :keyword ,placeholder:"キーワード検索",class:"header-search-input"%>
                      <% submit_tag %>
                    <% end %>
                    <i class="fas fa-search "></i>
                  </div>
                  
                </div>
              </div>
              <div class="header-right-container">
                <% if user_signed_in? %>                               
                  <div class="p-2 m-1 text-white header-user-name"><%= current_user.name %></div>
                  <div class="user_header_image nav-item p-2 m-1">
                    <% if current_user.image.attached? %>
                      <%= image_tag current_user.image ,style: "border-radius: 50%",:size => "65x65" %>
                    <%else%>
                      <%= image_tag "upper_body-2.png",style: "border-radius: 50%",:size => "65x65"%>
                    <%end%>
                  </div>
                <% else %>  
                  <%= link_to"ログイン","/users/sign_in",class:"home-link-user p-2 m-1 btn btn-outline-primary text-white bg-primary"%>
                  <%= link_to"新規登録","/users/sign_up",class:"home-link-user p-2 m-1 btn btn-outline-info text-white bg-info"%>
                <% end %>                                      

                
                <div class="user_headnav p-2 bg-light text-left">  
                  <ul class="p-2 mb-0 header-nav-menu">
                    <li class="mb-1"><%=link_to "ルーム登録",new_room_path,class: "nav_link",:style=>"color:black;"%></li>
                    <li class="mb-1"><%=link_to "予約済みルーム一覧",reservations_path,class: "nav_link",:style=>"color:black;" %></li>
                    <li class="mb-1"><%=link_to "登録済みルーム一覧",rooms_posts_path,class: "nav_link",:style=>"color:black;"%></li>
                    <li class="mb-1"><%=link_to "設定",account_path,class: "nav_link",:style=>"color:black;"%></li>
                    <li class="mb-1"><%=link_to "ログアウト",destroy_user_session_path,method: :delete,class: "nav_link",:style=>"color:black;"%></li>
                  </ul>
                </div>   
              </div>
            </div>

          <script>
            $('.user_headnav').hide();
            $('.user_header_image').on('click',function(){
              $('.user_headnav').slideToggle();
            })
          </script>
    </header>






    <main>
      <div class="clearfix">
        <%= notice %>
        <%= alert %>
      </div>
      <%= yield %>
    </main>






    <footer class="footer">
        <p>© 2020 POTEPAN.INC.</p>
    </footer>



  </body>
</html>

app/views/shared/_error.html.erb
<%if obj.errors.any?%>
    <% obj.errors.full_messages.each do |message| %>
      <ul class="m-0">
        <li class="text-danger"><%= message %></li>
      </ul>
    <%end%>
<%end%>
  
      

app/views/shared/_error_form.html.erb
<div class="notificattions"> 
<% if object.errors.any? %>
   <ul class="errors-messages-box">
     <% object.errors.full_messages.each do |message| %>
       <li class="errors-messages"><%= message %></li>
     <% end %>
   </ul>
   <% end %>
</div>  

app/views/shared/_footer.html.erb
<p>©︎ 2020 POTEPAN.INC.</p>

app/views/shared/_header.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 header-container shadow-sm">
  <div class="header-left-container">
    <%= link_to root_path do %>
    <img class="my-0 mr-md-auto font-weight-normal" id="home-logo" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png">
    <% end %>
    <div class="header-search-container mt-3">
      <div class="header-search-box">
        <%= form_with url: rooms_search_path,method: :get,local: true do |f| %>
          <%= f.text_field :area ,placeholder:"エリア検索",class:"header-search-input"%>
          <% submit_tag %>
        <% end %>
        <i class="fas fa-map-marker-alt"></i>
      </div>
      
      <div class="header-search-box">
        <%= form_with url: rooms_search_path,method: :get,local: true do |f| %>
          <%= f.text_field :keyword ,placeholder:"キーワード検索",class:"header-search-input"%>
          <% submit_tag %>
        <% end %>
        <i class="fas fa-search "></i>
      </div>
      
    </div>
  </div>
  <div class="header-right-container">
    <% if user_signed_in? %>
      <div class="p-2 m-1 text-white header-user-name"><%= current_user.name %></div>
      <div class="user_header_image nav-item p-2 m-1">
        <% if current_user.image.attached? %>
          <%= image_tag current_user.image ,style: "border-radius: 50%",:size => "65x65" %>
        <%else%>
          <%= image_tag "upper_body-2.png",style: "border-radius: 50%",:size => "65x65"%>
        <%end%>
      </div>
    <% else %>  
      <%= link_to"ログイン","/users/sign_in",class:"home-link-user p-2 m-1 btn btn-outline-primary text-white bg-primary"%>
      <%= link_to"新規登録","/users/sign_up",class:"home-link-user p-2 m-1 btn btn-outline-info text-white bg-info"%>
    <% end %>  
      <%= render "shared/headnav" %>  
  </div>
</div>

<script>
  $('.user_headnav').hide();
  $('.user_header_image').on('click',function(){
    $('.user_headnav').slideToggle();
  })
</script>

app/views/shared/_headnav.html.erb
<div class="user_headnav p-2 bg-light text-left">  
  <ul class="p-2 mb-0 header-nav-menu">
    <li class="mb-1"><%=link_to "ルーム登録",new_room_path,class: "nav_link",:style=>"color:black;"%></li>
    <li class="mb-1"><%=link_to "予約済みルーム一覧",reservations_path,class: "nav_link",:style=>"color:black;" %></li>
    <li class="mb-1"><%=link_to "登録済みルーム一覧",rooms_posts_path,class: "nav_link",:style=>"color:black;"%></li>
    <li class="mb-1"><%=link_to "設定",account_path,class: "nav_link",:style=>"color:black;"%></li>
    <li class="mb-1"><%=link_to "ログアウト",destroy_user_session_path,method: :delete,class: "nav_link",:style=>"color:black;"%></li>
  </ul>
</div>   

app/views/shared/_roombar.html.erb
<div class="sidebar_content">
  <ul class="p-0">
    <li class="roombar_tab text-left h5 p-0"><%=link_to"基本情報",new_room_path,class: "roombar_link",:style=>"color:#000;"%></li> 
  </ul>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar_content">
  <ul>
    <% if current_page?(account_path) %>
    <li class="sidebar_tab active"><%=link_to"アカウント","/account",class: "sidebar_link account"%></li> 
    <li class="sidebar_tab "><%=link_to"プロフィール","/profile",class: "sidebar_link "%></li>
    <% else %>
    <li class="sidebar_tab "><%=link_to"アカウント","/account",class: "sidebar_link "%></li> 
    <li class="sidebar_tab active" ><%=link_to"プロフィール","/profile",class: "sidebar_link account"%></li>
    <% end %>
    </ul>
  
  
</div>